bouchon.messages:
  # Errors
  ERR-INIT-001: "Le endpoint n''est pas géré"
  ERR-INIT-002: "Le dossier data ( ${bouchon.folder.data} ) n''existe pas"
  ERR-INIT-003: "Le type de regex ''{0}'' n''existe pas"
  ERR-INIT-004: "Une erreur est survenue lors de l''initialisation du endpoint ''{0}'': {1}"
  ERR-INIT-005: "L''URL requiert une regex d''un type ''{0}'' qui n''existe pas"
  ERR-INIT-006: "L''URL possède plusieurs fois la regex ''{0}''"
  ERR-INIT-007: "L''URL et le fichier ne requierent pas les mêmes regex"

  ERR-MSG-001: "Le message ''{0}'' n''existe pas"

  # Réception d'une requête
  ENDPOINT-001: "Plusieurs endpoints peuvent correspondre à la demande: {0}"
  ENDPOINT-002: "Aucun endpoint n''a été trouvé pour la recherche ''{0}''"
  REQUEST-001: "La requête '{0}' ne correspond pas au endpoint '{1}'"

  # Debug
  DEBUG-INIT-001: "Enregistrement du endpoint ''{0}''"
  DEBUG-INIT-002: "Le dossier ''{0}'' n''a pas été initialisé"
  DEBUG-REGEX-001: "La regex ''{0}'' a été trouvée"
  DEBUG-REGEX-002: "Remplacement de ''{0}'' par ''{1}'' dans le string ''{2}''"

  DEBUG-FILE-001: "Remplacement de ''{0}'' par ''{1}'' dans le template de fichier ''{2}''"

  FILE-READING-001: "Une erreur est survenue pendant la lecture du fichier '{0}'"

  # Configuration des endpoints
  CONFIG-ENDPOINT-UPLOAD: "Traitement du fichier de endpoints ''{0}''"