bouchon.messages:
  # Errors
  ERR-INIT-001: "Le endpoint n''est pas géré"
  ERR-INIT-002: "Le dossier data ( ${bouchon.folder.data} ) n''existe pas"
  ERR-INIT-003: "Le type de regex ''{0}'' n''existe pas"
  ERR-INIT-004: "Une erreur est survenue lors de l''initialisation du endpoint ''{0}'': {1}"
  ERR-INIT-005: "L''URL requiert une regex d''un type ''{0}'' qui n''existe pas"
  ERR-INIT-006: "L''URL possède plusieurs fois la regex ''{0}''"
  ERR-INIT-007: "L''URL et le fichier ne requierent pas les mêmes regex"
  INIT-ENDPOINT-ALREADY-EXISTS: "Le endpoint avec le nom ''{0}'' existe déjà"

  ERR-MSG-001: "Le message ''{0}'' n''existe pas"

  # Réception d'une requête
  ENDPOINT-001: "Plusieurs endpoints peuvent correspondre à la demande: {0}"
  ENDPOINT-002: "Aucun endpoint n''a été trouvé pour la recherche ''{0}''"
  REQUEST-001: "La requête '{0}' ne correspond pas au endpoint '{1}'"

  # Debug
  ENDPOINT-LOADING: "Enregistrement du endpoint ''{0}''"
  DEBUG-INIT-002: "Le dossier ''{0}'' n''a pas été initialisé"
  DEBUG-REGEX-001: "La regex ''{0}'' a été trouvée"
  DEBUG-REGEX-002: "Remplacement de ''{0}'' par ''{1}'' dans le string ''{2}''"

  DEBUG-FILE-001: "Remplacement de ''{0}'' par ''{1}'' dans le template de fichier ''{2}''"

  FILE-READING-001: "Une erreur est survenue pendant la lecture du fichier '{0}'"

  # Configuration des endpoints
  CONFIG-ENDPOINT-LOADING: "Traitement du fichier de endpoints ''{0}''"
  CONFIG-ENDPOINT-COMPLETE-RELOAD: "Rechargement complet des endpoints"
  CONFIG-ENDPOINT-UPLOADING: "Upload du fichier de endpoints ''{0}'' avec comme nom de destination ''{1}''"
  CONFIG-ENDPOINT-UPLOADING-FILENAME-ALREADY-TAKEN: "Le nom de destination ''{0}'' est déjà pris, on essaie un nouveau"
  CONFIG-ENDPOINT-UPLOADING-ERROR: "Une erreur est survenue pendant l''import du fichier ''{0}''"
  CONFIG-ENDPOINT-UPLOADING-VERIFICATION: "Verification du fichier ''{0}''"
  CONFIG-ENDPOINT-UPLOADING-VERIFICATION-ERROR: "La vérification suivante est en erreur: {0}"
  CONFIG-ENDPOINT-UPLOADING-VERIFICATION-FAILED: "Le fichier ''{0}'' n'est pas valide pour les raisons suivantes: {1}"
  CONFIG-ENDPOINT-FILE-UPLOAD-EXTENSION-ERROR: "L''extension du fichier doit être parmis la liste suivante: {0}"
  CONFIG-FOLDER-NOT-EXISTS: "Le dossier de configuration ''{0}'' n'existe pas"
  CONFIG-ENDPOINT-DELETE: "Suppression du fichier ''{0}'' en cours"
  CONFIG-ENDPOINT-DELETE-FILE-NOT-FOUND: "Impossible de supprimer le fichier ''{0}'' car il n''existe pas"
  CONFIG-ENDPOINT-DELETE-FILE-DELETED: "Fichier ''{0}'' supprimé"
  CONFIG-ENDPOINT-DELETE-FILE-NOT-DELETED: "Fichier ''{0}'' non supprimé"

  # Statut des endpoints
  ENDPOINT-STATUT-OK: "OK"
  ENDPOINT-STATUT-KO: "KO"

