bouchon.messages:
  # Errors
  ERR-INIT-001: "Le endpoint n''est pas géré"
  ERR-INIT-002: "Le dossier data ( ${bouchon.folder.data} ) n''existe pas"
  ERR-INIT-003: "Le type de regex ''{0}'' n''existe pas"
  ERR_INIT-004: "Une erreur est survenue lors de l''initialisation du endpoint ''{0}''"

  # Debug
  DEBUG-INIT-001: "Enregistrement du endpoint ''{0}''"
  DEBUG-INIT-002: "Le dossier ''{0}'' n''a pas été initialisé"
