bouchon:
  endpoints:
    - name: test1
      folderName: folder1
      urlTemplate: url1{numberA}{numberA}
      fileTemplate: file1
      parameters:
        - tag: numberA
          type: number
        - tag: title1
          type: string
    - name: test2
      folderName: folder2
      urlTemplate: url2{blabl}
      fileTemplate: file2
  test: test
  folder:
    data: "path_to_data_folder"