logging:
  file:
    path: /mnt/logs
  pattern:
    console: "%d [T-%T] (%X{request-id}) %highlight{[%-6p] %c{2.}(%F:%L) - %m%n}"
    file: "%d [T-%T] (%X{request-id}) [%-6p] %c{1.}(%F:%L) - %m%n"
  level:
    root: "info"
    me.vcouturier: "debug"

