name: Docker build

on:
  push:
    branches:
      - feature/cicd

jobs:
  versions:
    uses: ./.github/workflows/gradle-get-versions.yml

  build:
    runs-on: ubuntu-latest
    needs: versions
    steps:
      - name: Print context
        run: |
          echo "${{ needs.versions }} - ${{ needs.versions.outputs }} - raw_version: ${{ needs.versions.outputs.raw_version }} - version: ${{ needs.versions.outputs.version }} - is_snapshot: ${{ needs.versions.outputs.is_snapshot }}"
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle - Prepare build
        uses: gradle/gradle-build-action@v2

      - name: Gradle - Build
        run: gradle build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/junit/**/*.xml

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: build

      - name: Caching files
        uses: actions/cache@v2
        with:
          path: |
            ./build/libs/bouchon-${{ needs.versions.outputs.raw_version }}.jar
          key: ${{ needs.versions.outputs.raw_version }}-artifacts-${{ github.run_id }}
    outputs:
      raw-project-version: ${{ needs.versions.outputs.raw_version }}
      cache-key: ${{ needs.versions.outputs.raw_version }}-artifacts-${{ github.run_id }}

  docker-build-push:
    needs: [versions, build]
    uses: ./.github/workflows/docker-push.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      jar-path: ./build/libs/bouchon-${{ needs.versions.outputs.raw_version }}.jar
      image-tag: ${{ needs.versions.outputs.raw_version }}
      docker-build-args: |
        CONFIG_FOLDER=./config
      docker-push: true
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
