name: Docker build

on:
  push:
    branches:
      - feature/cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List all files
        run: |
          ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
      - run: gradle build
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/junit/**/*.xml
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: build # optional
      - name: List all files
        run: |
          ls
       
