name: Docker build

on:
  push:
    branches:
      - feature/cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List all files
        run: |
          ls
