name: Docker build

on:
  push:
    branches:
      - feature/cicd

jobs:
  versions:
    uses: ./.github/workflows/gradle-get-versions.yml

  build:
    needs: versions
    uses: ./.github/workflows/gradle-build.yml
    with:
      raw_version: ${{ needs.versions.outputs.raw_version }}
      java_version: "11"
      java_distrib: "adopt"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  docker-build-push:
    needs: [versions, build]
    uses: ./.github/workflows/docker-push.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      jar-path: ./build/libs/bouchon-${{ needs.versions.outputs.raw_version }}.jar
      image-tag: ${{ needs.versions.outputs.raw_version }}
      docker-build-args: |
        CONFIG_FOLDER=./config
      docker-push: true
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
