name: Docker build

on:
  push:
    branches:
      - feature/cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List all files
        run: |
          ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
      - name: List all files
        run: |
          ls
       
