name: Docker buidl & push workflow

on:
  workflow_call:
    inputs:
      docker-build-args:
        required: true
        type: string
      image-version:
        required: true
        type: string
    secrets:
      username:
        required: true
      token:
        required: true

jobs:
  docker_build_push:
    name: Build dockerfile and push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Docker - login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Docker - build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: coutcout/bouchon:${{ inputs.image-version }}
          build-args: ${{ inputs.docker-build-args }}
