name: Gradle - Get versions of project

on:
  workflow_call:
    outputs:
      raw_version:
        description: "Project version without modification"
        value: ${{ jobs.get_versions_jobs.raw_version }}
      version:
        description: "Project version without potential suffix"
        value: ${{ jobs.get_versions_jobs.version }}
      is_snapshot:
        description: "Project version is a snapshot"
        value: ${{ jobs.get_versions_jobs.is_snapshot }}

jobs:
  get_versions_job:
    name: Get versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          RAW_BUILD_VERSION=$(grep "^version" build.gradle | sed -E 's/^version.*?\x27(.*?)\x27/\1/')
          echo "raw_project_version=$RAW_BUILD_VERSION" >> $GITHUB_ENV
          BUILD_VERSION=$(echo $RAW_BUILD_VERSION | sed -E 's/([0-9]*?\.[0-9]*?\.[0-9]*?).*/\1/')
          echo "project_version=$BUILD_VERSION" >> $GITHUB_ENV
          [[ $RAW_BUILD_VERSION = *-SNAPSHOT ]] && IS_SNAPSHOT=true || IS_SNAPSHOT=false
          echo "is_snapshot=$IS_SNAPSHOT" >> $GITHUB_ENV
    outputs:
      raw_version: ${{ env.raw_project_version }}
      version: ${{ env.project_version }}
      is_snapshot: ${{ env.is_snapshot }}