name: Release workflow

on:
  push:
    tags:
      - v*

jobs:
  versions:
    uses: ./.github/workflows/gradle-get-versions.yml

  build:
    needs: versions
    uses: ./.github/workflows/gradle-build.yml
    with:
      raw_version: ${{ needs.versions.outputs.raw_version }}
      java_version: "11"
      java_dist: "adopt"
      tag_version: ${{ github.ref_name }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  increment_version:
    needs: [build]
    name: Incrementation of project version
    uses: ./.github/workflows/gradle-increment-version.yml
    with:
      group_to_increment: "patch"
      java_version: "11"
      java_dist: "adopt"

  docker-build-push:
    needs: [versions, build]
    uses: ./.github/workflows/docker-push.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      jar-path: ./build/libs/bouchon-${{ needs.versions.outputs.raw_version }}.jar
      image-tag: ${{ needs.versions.outputs.raw_version }}
      docker-build-args: |
        CONFIG_FOLDER=./config
      docker-push: true
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
