name: Snapshot workflow

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  versions:
    uses: ./.github/workflows/gradle-get-versions.yml

  build:
    needs: versions
    uses: ./.github/workflows/gradle-test.yml
    with:
      raw_version: ${{ needs.versions.outputs.raw_version }}
      java_version: "11"
      java_dist: "adopt"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}